---

- name: install packages
  yum: "{{ compute_packages }}"
  tags: compute

- name: increase resource limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop: "{{ compute_limits }}"
  tags: compute

- name: create tuned HPC profile directory
  file:
    path: /etc/tuned/hpc-compute
    state: directory
  tags: compute

- name: copy HPC tuned profile
  copy:
    src: tuned-hpc.conf
    dest: /etc/tuned/hpc-compute/tuned.conf
  register: result
  tags: compute

- name: enable HPC tuned profile
  command: tuned-adm profile hpc-compute
  when: result.changed
  tags: compute

- name: copy sysctl configuration
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/98-macc.conf
  register: result
  tags: compute

- name: reload sysctl configuration
  command: /usr/sbin/sysctl -p
  when: result.changed
  tags: compute

- name: create destination mount dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ compute_mounts }}"
  tags: compute

- name: mount defined mounts
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
  loop: "{{ compute_mounts }}"
  tags: compute